// API 설정 파일
// 현재 접속한 도메인으로 백엔드 URL 자동 설정
const getBaseUrl = () => {
  // 환경변수가 있으면 우선 사용
  if (import.meta.env.VITE_BACKEND_API_BASE_URL) {
    return import.meta.env.VITE_BACKEND_API_BASE_URL;
  }
  // 없으면 현재 접속한 도메인 사용
  const hostname = window.location.hostname;
  const protocol = window.location.protocol;
  return `${protocol}//${hostname}:8080`;
};

const API_CONFIG = {
  BASE_URL: getBaseUrl(),
  ENDPOINTS: {
    LOGIN: '/login',
    MEMBER_EXIST: '/member/exist',
    MEMBER_JOIN: '/member/join',
    MEMBER_INFO: '/member/info',
    MEMBER_ACTIVE_MEMBERS: '/member/active-members',
    MEMBER_CHANGE_PASSWORD: '/member/changepassword',
    JWT_REFRESH: '/jwt/refresh',
    MEMBER_SEND_CODE: '/member/send-code',
    MEMBER_VERIFY_CODE: '/member/verify-code',
    MEMBER_RESET_PASSWORD: '/member/reset-password',
    DEPARTMENTS: '/departments',
    ADD_DEPARTMENT: '/addDepartment',
    UPDATE_DEPARTMENT: '/updateDepartment',
    DELETE_DEPARTMENT: '/deleteDepartment',
    POSITIONS: '/positions',
    ADD_POSITION: '/addPosition',
    UPDATE_POSITION: '/updatePosition',
    DELETE_POSITION: '/deletePosition',
    APPROVAL_TOTAL: '/approval/total',
    APPROVAL_IN_PROGRESS: '/approval/inProgress',
    APPROVAL_COMPLETED: '/approval/completed',
    APPROVAL_MY_SUBMITTED: '/approval/mySubmitted',
    APPROVAL_MY_PENDING: '/approval/mypending',
    APPROVAL_ALL: '/approval/allApprovals',
    APPROVAL_DRAFTING: '/approval/temporarySavedApprovals',
    APPROVAL_IN_PROGRESS_LIST: '/approval/inProgressApprovals',
    APPROVAL_RETURENED: '/approval/returnedApprovals',
    APPROVAL_APPROVED: '/approval/completedApprovals',

    // 관리자용 직원,직급,부서관리
    MEMBER_MEMBERS: '/admin/members',
    MEMBER_RETIRED_MEMBERS: '/admin/retired-members',
    MEMBER_DEACTIVATE: '/admin/deactivate',
    MEMBER_UPDATE: '/admin/update',
    MEMBER_DELETE: '/admin/delete',

    // 기안서 작성 관련
    APPROVAL_ADD_DRAFT: '/approvalDetail/addDraft',
    APPROVAL_TEMPORARY_DRAFT: '/approvalDetail/temporaryDraft',
    APPROVAL_GET_DRAFT: '/approvalDetail/getDraft',
    APPROVAL_GET_DETAIL: '/approvalDetail',
    APPROVAL_APPROVE: '/approval/doApproval',
    APPROVAL_REJECT: '/approval/doReject',
    APPROVAL_FILE_DOWNLOAD: '/approvalDetail/file/download',
    APPROVAL_DELETE: '/approvalDetail/delete',
    APPROVAL_CANCEL: '/approvalDetail/cancel',
    APPROVAL_ADD_COMMENTS: '/approval/addcomments',
    APPROVAL_EDIT_COMMENT: '/approval/editcomment',
    APPROVAL_DELETE_COMMENT: '/approval/deletecomment',

    APPROVAL_FORMS: '/form/list',
    APPROVAL_FORM_DETAIL: '/form',
    FORM_ADD: '/form/addForm',
    FORM_UPDATE: '/form/update',
    FORM_DELETE: '/form/delete',
  },
};

// API URL 생성 헬퍼 함수
export const getApiUrl = (endpoint) => {
  return `${API_CONFIG.BASE_URL}${endpoint}`;
};

// 자주 사용하는 API URL들
export const API_URLS = {
  LOGIN: getApiUrl(API_CONFIG.ENDPOINTS.LOGIN),
  MEMBER_EXIST: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_EXIST),
  MEMBER_JOIN: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_JOIN),
  MEMBER_INFO: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_INFO),
  MEMBER_UPDATE: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_UPDATE),
  MEMBER_DELETE: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_DELETE),
  MEMBER_CHANGE_PASSWORD: getApiUrl(
    API_CONFIG.ENDPOINTS.MEMBER_CHANGE_PASSWORD
  ),
  JWT_REFRESH: getApiUrl(API_CONFIG.ENDPOINTS.JWT_REFRESH),
  MEMBER_SEND_CODE: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_SEND_CODE),
  MEMBER_VERIFY_CODE: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_VERIFY_CODE),
  MEMBER_RESET_PASSWORD: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_RESET_PASSWORD),
  MEMBER_MEMBERS: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_MEMBERS),
  MEMBER_ACTIVE_MEMBERS: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_ACTIVE_MEMBERS),
  MEMBER_RETIRED_MEMBERS: getApiUrl(
    API_CONFIG.ENDPOINTS.MEMBER_RETIRED_MEMBERS
  ),
  MEMBER_DEACTIVATE: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_DEACTIVATE),
  DEPARTMENTS: getApiUrl(API_CONFIG.ENDPOINTS.DEPARTMENTS),
  ADD_DEPARTMENT: getApiUrl(API_CONFIG.ENDPOINTS.ADD_DEPARTMENT),
  UPDATE_DEPARTMENT: getApiUrl(API_CONFIG.ENDPOINTS.UPDATE_DEPARTMENT),
  DELETE_DEPARTMENT: getApiUrl(API_CONFIG.ENDPOINTS.DELETE_DEPARTMENT),
  POSITIONS: getApiUrl(API_CONFIG.ENDPOINTS.POSITIONS),
  ADD_POSITION: getApiUrl(API_CONFIG.ENDPOINTS.ADD_POSITION),
  UPDATE_POSITION: getApiUrl(API_CONFIG.ENDPOINTS.UPDATE_POSITION),
  DELETE_POSITION: getApiUrl(API_CONFIG.ENDPOINTS.DELETE_POSITION),

  APPROVAL_TOTAL: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_TOTAL),
  APPROVAL_COMPLETED: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_COMPLETED),
  APPROVAL_MY_SUBMITTED: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_MY_SUBMITTED),
  APPROVAL_MY_PENDING: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_MY_PENDING),

  // progresslistcontent 진행목록
  APPROVAL_ALL: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_ALL),
  APPROVAL_DRAFTING: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_DRAFTING),
  APPROVAL_IN_PROGRESS: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_IN_PROGRESS),
  APPROVAL_IN_PROGRESS_LIST: getApiUrl(
    API_CONFIG.ENDPOINTS.APPROVAL_IN_PROGRESS_LIST
  ),
  APPROVAL_RETURNED: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_RETURENED),
  APPROVAL_APPROVED: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_APPROVED),

  // 기안서 작성 관련
  APPROVAL_ADD_DRAFT: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_ADD_DRAFT),
  APPROVAL_TEMPORARY_DRAFT: getApiUrl(
    API_CONFIG.ENDPOINTS.APPROVAL_TEMPORARY_DRAFT
  ),
  APPROVAL_GET_DRAFT: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_GET_DRAFT),
  APPROVAL_APPROVE: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_APPROVE),
  APPROVAL_REJECT: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_REJECT),
  APPROVAL_FILE_DOWNLOAD: getApiUrl(
    API_CONFIG.ENDPOINTS.APPROVAL_FILE_DOWNLOAD
  ),
  APPROVAL_DELETE: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_DELETE),
  APPROVAL_CANCEL: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_CANCEL),
  APPROVAL_ADD_COMMENTS: (approvalNo) =>
    `${getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_ADD_COMMENTS)}/${approvalNo}`,
  APPROVAL_EDIT_COMMENT: (approvalNo) =>
    `${getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_EDIT_COMMENT)}/${approvalNo}`,
  APPROVAL_DELETE_COMMENT: (approvalNo) =>
    `${getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_DELETE_COMMENT)}/${approvalNo}`,
  APPROVAL_FORMS: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_FORMS),
  APPROVAL_FORM_DETAIL: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_FORM_DETAIL),
  FORM_ADD: getApiUrl(API_CONFIG.ENDPOINTS.FORM_ADD),
  FORM_UPDATE: getApiUrl(API_CONFIG.ENDPOINTS.FORM_UPDATE),
  FORM_DELETE: getApiUrl(API_CONFIG.ENDPOINTS.FORM_DELETE),
};

export default API_CONFIG;
