// API 설정 파일
const API_CONFIG = {
  BASE_URL:
    import.meta.env.VITE_BACKEND_API_BASE_URL || 'http://localhost:8080',
  ENDPOINTS: {
    LOGIN: '/login',
    MEMBER_EXIST: '/member/exist',
    MEMBER_JOIN: '/member/join',
    MEMBER_INFO: '/member/info',
    MEMBER_MEMBERS: '/member/members',
    MEMBER_ACTIVE_MEMBERS: '/member/active-members',
    MEMBER_RETIRED_MEMBERS: '/member/retired-members',
    MEMBER_UPDATE: '/member/update',
    MEMBER_DELETE: '/member/delete',
    MEMBER_DEACTIVATE: '/member/deactivate',
    MEMBER_CHANGE_PASSWORD: '/member/changepassword',
    JWT_REFRESH: '/jwt/refresh',
    MEMBER_SEND_CODE: '/member/send-code',
    MEMBER_VERIFY_CODE: '/member/verify-code',
    MEMBER_RESET_PASSWORD: '/member/reset-password',
    DEPARTMENTS: '/departments',
    ADD_DEPARTMENT: '/addDepartment',
    UPDATE_DEPARTMENT: '/updateDepartment',
    DELETE_DEPARTMENT: '/deleteDepartment',
    POSITIONS: '/positions',
    ADD_POSITION: '/addPosition',
    UPDATE_POSITION: '/updatePosition',
    DELETE_POSITION: '/deletePosition',
    APPROVAL_TOTAL: '/approval/total',
    APPROVAL_IN_PROGRESS: '/approval/inProgress',
    APPROVAL_COMPLETED: '/approval/completed',
    APPROVAL_MY_SUBMITTED: '/approval/mySubmitted',
    APPROVAL_MY_PENDING: '/approval/mypending',
    APPROVAL_ALL: '/approval/allAprovals',
    APPROVAL_DRAFTING: '/approval/temporarySavedApprovals',
    APPROVAL_RETURENED: '/approval/returnedApprovals',
    APPROVAL_APPROVED: '/approval/completedApprovals',
  },
};

// API URL 생성 헬퍼 함수
export const getApiUrl = (endpoint) => {
  return `${API_CONFIG.BASE_URL}${endpoint}`;
};

// 자주 사용하는 API URL들
export const API_URLS = {
  LOGIN: getApiUrl(API_CONFIG.ENDPOINTS.LOGIN),
  MEMBER_EXIST: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_EXIST),
  MEMBER_JOIN: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_JOIN),
  MEMBER_INFO: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_INFO),
  MEMBER_UPDATE: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_UPDATE),
  MEMBER_DELETE: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_DELETE),
  MEMBER_CHANGE_PASSWORD: getApiUrl(
    API_CONFIG.ENDPOINTS.MEMBER_CHANGE_PASSWORD
  ),
  JWT_REFRESH: getApiUrl(API_CONFIG.ENDPOINTS.JWT_REFRESH),
  MEMBER_SEND_CODE: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_SEND_CODE),
  MEMBER_VERIFY_CODE: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_VERIFY_CODE),
  MEMBER_RESET_PASSWORD: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_RESET_PASSWORD),
  MEMBER_MEMBERS: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_MEMBERS),
  MEMBER_ACTIVE_MEMBERS: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_ACTIVE_MEMBERS),
  MEMBER_RETIRED_MEMBERS: getApiUrl(
    API_CONFIG.ENDPOINTS.MEMBER_RETIRED_MEMBERS
  ),
  MEMBER_DEACTIVATE: getApiUrl(API_CONFIG.ENDPOINTS.MEMBER_DEACTIVATE),
  DEPARTMENTS: getApiUrl(API_CONFIG.ENDPOINTS.DEPARTMENTS),
  ADD_DEPARTMENT: getApiUrl(API_CONFIG.ENDPOINTS.ADD_DEPARTMENT),
  UPDATE_DEPARTMENT: getApiUrl(API_CONFIG.ENDPOINTS.UPDATE_DEPARTMENT),
  DELETE_DEPARTMENT: getApiUrl(API_CONFIG.ENDPOINTS.DELETE_DEPARTMENT),
  POSITIONS: getApiUrl(API_CONFIG.ENDPOINTS.POSITIONS),
  ADD_POSITION: getApiUrl(API_CONFIG.ENDPOINTS.ADD_POSITION),
  UPDATE_POSITION: getApiUrl(API_CONFIG.ENDPOINTS.UPDATE_POSITION),
  DELETE_POSITION: getApiUrl(API_CONFIG.ENDPOINTS.DELETE_POSITION),

  APPROVAL_TOTAL: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_TOTAL),
  APPROVAL_IN_PROGRESS: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_IN_PROGRESS),
  APPROVAL_COMPLETED: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_COMPLETED),
  APPROVAL_MY_SUBMITTED: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_MY_SUBMITTED),
  APPROVAL_MY_PENDING: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_MY_PENDING),

  // progresslistcontent 진행목록
  APPROVAL_ALL: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_ALL),
  APPROVAL_DRAFTING: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_DRAFTING),
  APPROVAL_IN_PROGRESS: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_IN_PROGRESS),
  APPROVAL_RETURENED: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_RETURENED),
  APPROVAL_APPROVED: getApiUrl(API_CONFIG.ENDPOINTS.APPROVAL_APPROVED),
};

export default API_CONFIG;
